name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.EC2_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
        cd /home/${{ secrets.EC2_USER }}/Webapp_Project_1 || exit 1

        # Fetch latest changes and reset hard to match remote main branch
        git fetch origin
        git reset --hard origin/main

        # Install http-server if not present
        if ! command -v http-server &> /dev/null; then
          npm install -g http-server
        fi

        # Kill any process on port 8080 to avoid conflicts
        fuser -k 8080/tcp || true

        # Start http-server in background with nohup
        nohup http-server -p 8080 > server.log 2>&1 &
        EOF
